"""Publish only a fully restored original snapshot; preserve all existing research."""
from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil,subprocess,sys,os
SRC=Path(sys.argv[1]).resolve();REPO=Path.cwd();DEST=REPO/'experiments/root_st073/snapshot'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def gitblob(p):
 b=p.read_bytes();return hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()
expected=json.loads((SRC/'MANIFEST.json').read_text())['files'];receipt=json.loads((SRC.parent/'st073_transport_receipt.json').read_text())
if DEST.exists():raise ValueError('Refuse to overwrite a published snapshot')
for name in list(expected)+['MANIFEST.json']:
 p=SRC/name
 if name in expected and sha(p)!=expected[name]:raise ValueError('Changed payload '+name)
 dst=DEST/name;dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,dst)
readme=REPO/'README.md';checkpoint=REPO/'docs/CURRENT_CHECKPOINT.md'
if gitblob(readme)!='a36a170d5bf1b42653ea487e8c8978bf502f5367':raise ValueError('README changed; review before updating')
if gitblob(checkpoint)!='f77c9db43852d5f33f12a2bb504f39802d66d2c7':raise ValueError('Checkpoint changed; review before updating')
notice='## Latest synchronized data: ST073\n\nThe [complete ST073 snapshot](experiments/root_st073/snapshot/README.md) is now stored in this repository, including both model definitions, the executable recurrence and dependencies, actual coefficient/field NPZ snapshots, historical validation reports, tests, and failed controls. All 173 original payload files are bound by their unchanged SHA256 manifest. See the [synchronization record](experiments/root_st073/SYNC_STATUS.md).\n\nST073-V passes its reported **local sampled** full-momentum checks, not the original whole-space benchmark. It is a local unforced field on `X <= 1/64`, `|eta| <= 0.5`; outer matching, finite global energy, non-axisymmetric corrections, and dynamic scale recurrence remain incomplete. Scientific flags and existing viewer/API defaults are unchanged. Scheduled agents remain paused.\n\n```bash\ncd experiments/root_st073/snapshot\npython -m pip install -r requirements.txt\npython verify_delivery.py\npython -m pytest -q -W error tests\npython replay.py --candidate ST073-V --k 6 --order 18 --out outputs/V_k6.json\n```\n\nThe final command can return 0 for its **local** check only. The following ST063/ST061 and viewer sections retain their distinct historical and global-benchmark scope.\n\n'
text=readme.read_text();first,rest=text.split('\n',1);readme.write_text(first+'\n\n'+notice+rest.lstrip('\n'))
text=checkpoint.read_text();first,rest=text.split('\n',1)
checkpoint.write_text(first+'\n\n## ST073 complete-data sync — 2026-09-24\n\nThe complete [ST073 local recurrence snapshot](../experiments/root_st073/snapshot/README.md) is now committed, not only referenced by a conversation ZIP. Its 173 original payload files and manifest are preserved. Use [SYNC_STATUS.md](../experiments/root_st073/SYNC_STATUS.md) for commands and exact availability. This does not replace ST063 as a geometry example or the existing ST054 viewer/ST006 API defaults. ST073 is local and unforced; global acceptance and scale-recursion capability remain false.\n\n'+rest.lstrip('\n'))
receipt.update({'published_utc':datetime.now(timezone.utc).isoformat(),'source_archive_name':'NS_ST073_Full_Local_Recurrence.zip','snapshot_path':'experiments/root_st073/snapshot','expected_snapshot_git_tree':'d38327ad388e595beb78470539ca526cf20ec972','workflow_run_id':os.environ.get('GITHUB_RUN_ID'),'staging_commit':os.environ.get('GITHUB_SHA'),'focused_software_tests':'18 tests passed in this workflow before publication','old_models_modified':False,'defaults_changed':False,'schedules_changed':False,'historical_reports_rewritten':False})
(DEST.parent/'SYNC_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n')
(DEST.parent/'SYNC_STATUS.md').write_text('# ST073 complete-data synchronization\n\nThis directory contains the complete original ST073 offline payload in `snapshot/`: **173 original files plus MANIFEST.json**, not download stubs. Models, numerical sources, all original NPZ snapshots, historical reports, tests, and failure controls are preserved byte-for-byte.\n\n## Run\n\nFrom the repository root:\n\n```bash\ncd experiments/root_st073/snapshot\npython -m pip install -r requirements.txt\npython verify_delivery.py\npython -m pytest -q -W error tests\npython replay.py --candidate ST073-V --k 6 --order 18 --out outputs/V_k6.json\n```\n\nThe last command reports **local** sampled momentum only. `pde_validated=false` and `global_field_ready=false` remain unchanged. This is not the whole-space fixed-force/energy benchmark, a matched exterior, a scale-recursion solution, or an accepted blow-up construction. No MATLAB viewer or scientific default is replaced.\n\n## Integrity and historical evidence\n\nOriginal archive SHA256: `c9b3089fb727c2834479037f7bbebc2262a35b05479890e392052203f5acc917`. Original payload manifest: [snapshot/MANIFEST.json](snapshot/MANIFEST.json). Synchronization receipt: [SYNC_RECEIPT.json](SYNC_RECEIPT.json).\n\nThe text and historical reports were transported verbatim. Deterministic binary snapshots were restored from the original immutable model/source/seed inputs, with exact long-double storage padding retained, and were admitted only after EVERY original SHA256 matched. The synchronization workflow then ran the 18 focused software tests. This is byte-integrity/packaging work, not new optimization or a newly independent scientific study. Historical package/test receipts inside the snapshot were not edited; their earlier statements about missing GitHub files describe the state before this sync. This status record supersedes those availability statements, not their scientific limitations.\n\nNo previous candidate, existing research path, paused-agent schedule, repository visibility or old evidence was removed or modified. Temporary write-enabled transport code is removed from the final tree after its one-time run.\n')
subprocess.run(['git','add','-f','experiments/root_st073','README.md','docs/CURRENT_CHECKPOINT.md'],check=True)
tree=subprocess.check_output(['git','write-tree'],text=True).strip()
snapshot=subprocess.check_output(['git','rev-parse',tree+':experiments/root_st073/snapshot'],text=True).strip()
if snapshot!='d38327ad388e595beb78470539ca526cf20ec972':raise ValueError('Final snapshot Git tree is not identical to original')
print('Exact original snapshot tree:',snapshot)
