"""Source heat-replacement discrepancy evaluator for the Kokuno outer schedule.

The corrected 2026-09-09 reader replaces the far power-law swirl by the
radial heat solution.  With ``y=log(X/X_tail)`` it sets

    X_K = exp(.2) X_tail,  X_b = exp(3) X_tail,
    chi_K = 0 for y<=.2, chi_K = 1 for y>=.5,
    E_new = E_cl * (1 + chi_K (Hcal(2d/X)-1)),

where ``d=1-eta^2`` and, on the terminal tail,

    E_cl = c_inf X^(-A) f_o(y),
    f_o = 1-rho_o psi_o, psi_o = 1-sigma((y-1)/2),
    A=1/2+h.

This module evaluates the three *actual heat-replacement* moment changes
``(Delta C_p, Delta S, Delta I_sub)`` generated by those formulas.  The flat
choice ``chi_K=sigma((y-.2)/.3)`` is a deterministic autonomous realization
of the source's allowed transition; the source only fixes its support/end
values.  ``X_tail``, ``c_inf`` and ``rho_o`` remain explicit schedule inputs:
this module does not claim to have recovered the source existence proof's
hidden numerical choices.

The result can be converted to the normalized target required by
``KokunoHeatDiscrepancyRepair``.  That conversion still requires the earlier
reserved-patch scales ``X_star,e_star`` from the outer schedule, so this is one
step short of a globally matched leading field.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import math
from pathlib import Path
from typing import Any

import numpy as np
from numpy.polynomial.legendre import leggauss
from scipy.special import roots_laguerre

from .kokuno_heat_exterior_profile import KokunoHeatExteriorProfile


SOURCE_REPOSITORY = "KokunoYumeto/yang-mills-interacting-workbench"
SOURCE_COMMIT = "143f6773feb424ad9ed3a8d116653200f20346b7"
SOURCE_PATH = "navier-stokes/navier_stokes_workbench.tex"
CORRECTED_RELEASE = "zenodo:22678406"
CORRECTED_RELEASE_DATE = "2026-09-09"
SCHEMA = "kokuno-heat-replacement-discrepancy-v1"

_SOURCE_FORMULAS = {
    "tail_coordinate": "y=log(X/X_tail), X_K=exp(.2)X_tail, X_b=exp(3)X_tail",
    "terminal_multiplier": (
        "f_o(y)=1-rho_o*psi_o(y), psi_o=1-sigma((y-1)/2), "
        "rho_o=c_o*h>0, 0<=f_o'/f_o<h/4"
    ),
    "power_tail": "E_cl=c_inf*X^(-A)*f_o(y), A=1/2+h",
    "heat_replacement": (
        "E_new=E_cl*(1+chi_K(y)*(Hcal(2*(1-eta^2)/X)-1)); "
        "chi_K=0 for y<=.2 and chi_K=1 for y>=.5"
    ),
    "discrepancies": (
        "Delta C_p=int delta(E^2)/(2X)dX; "
        "Delta S=-int delta(E^2)/2 dX; "
        "Delta I_sub=int sqrt(2X)*delta E dX"
    ),
    "repair_target": (
        "target_normalized=-(Delta C_p/e_*^2, "
        "Delta S/(X_*e_*^2), Delta I_sub/(X_*^(3/2)e_*))"
    ),
}

_TRUTH_BOUNDARY = {
    "public_reconstruction_source": True,
    "actual_heat_replacement_discrepancy_formula_executable": True,
    "source_heat_tail_ratios_instantiated": True,
    "source_chi_transition_endpoints_preserved": True,
    "autonomous_chi_transition_shape": True,
    "source_outer_schedule_numeric_choices_recovered": False,
    "earlier_reserved_patch_scales_recovered": False,
    "eta_smooth_repair_coefficients_reconstructed": False,
    "heat_compensation_completed": False,
    "core_to_heat_matching_completed": False,
    "global_leading_profile_reconstructed": False,
    "complete_kokuno_composite_velocity": False,
    "formal_full_domain_pde_gate_assessed": False,
    "pde_validated": False,
    "paper_exact": False,
    "openai_field_identified": False,
    "blowup_proved": False,
}


def _canonical_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), allow_nan=False)


def _finite_array(value: Any, name: str) -> np.ndarray:
    array = np.asarray(value, dtype=float)
    if not np.all(np.isfinite(array)):
        raise ValueError(f"{name} must contain only finite values")
    return array


def _flat_step(value: Any) -> np.ndarray:
    """The source C-infinity step sigma, evaluated without endpoint overflow."""

    s = _finite_array(value, "step_argument")
    out = np.zeros_like(s)
    out[s >= 1.0] = 1.0
    active = (s > 0.0) & (s < 1.0)
    if np.any(active):
        a = s[active]
        left = np.exp(-1.0 / (a * a))
        right = np.exp(-1.0 / ((1.0 - a) ** 2))
        out[active] = left / (left + right)
    return out


@dataclass(frozen=True)
class KokunoHeatReplacementDiscrepancy:
    """Evaluate the source heat-tail moment discrepancy for explicit tail scales."""

    h: float = 0.005
    X_tail: float = 1000.0
    c_inf: float = 1.0
    rho_o: float = 0.00025
    heat_quadrature_order: int = 96
    transition_quadrature_order: int = 192
    tail_quadrature_order: int = 96

    def __post_init__(self) -> None:
        h = float(self.h)
        X_tail = float(self.X_tail)
        c_inf = float(self.c_inf)
        rho_o = float(self.rho_o)
        if not math.isfinite(h) or not (0.0 < h < 1.0e-2):
            raise ValueError("h must satisfy the source construction bound 0<h<1e-2")
        if not math.isfinite(X_tail) or X_tail <= 0.0:
            raise ValueError("X_tail must be positive and finite")
        if not math.isfinite(c_inf) or c_inf <= 0.0:
            raise ValueError("c_inf must be positive and finite")
        if not math.isfinite(rho_o) or not (0.0 < rho_o < 0.1):
            raise ValueError("rho_o must lie in (0,0.1)")
        for name, value, lo, hi in (
            ("heat_quadrature_order", self.heat_quadrature_order, 32, 256),
            ("transition_quadrature_order", self.transition_quadrature_order, 64, 512),
            ("tail_quadrature_order", self.tail_quadrature_order, 32, 256),
        ):
            if isinstance(value, bool) or not isinstance(value, (int, np.integer)):
                raise TypeError(f"{name} must be an integer")
            if not lo <= int(value) <= hi:
                raise ValueError(f"{name} must lie in [{lo},{hi}]")
        object.__setattr__(self, "h", h)
        object.__setattr__(self, "X_tail", X_tail)
        object.__setattr__(self, "c_inf", c_inf)
        object.__setattr__(self, "rho_o", rho_o)
        object.__setattr__(self, "heat_quadrature_order", int(self.heat_quadrature_order))
        object.__setattr__(
            self, "transition_quadrature_order", int(self.transition_quadrature_order)
        )
        object.__setattr__(self, "tail_quadrature_order", int(self.tail_quadrature_order))
        if self.max_terminal_log_slope() >= 0.25 * h:
            raise ValueError("rho_o violates the source terminal bound f_o'/f_o<h/4")

    @property
    def A(self) -> float:
        return 0.5 + self.h

    @property
    def X_K(self) -> float:
        return math.exp(0.2) * self.X_tail

    @property
    def X_b(self) -> float:
        return math.exp(3.0) * self.X_tail

    def _heat(self) -> KokunoHeatExteriorProfile:
        return KokunoHeatExteriorProfile(
            h=self.h, c_inf=self.c_inf, quadrature_order=self.heat_quadrature_order
        )

    @staticmethod
    def chi_K(y: Any) -> np.ndarray:
        """Autonomous flat realization of the source .2-to-.5 transition."""

        values = _finite_array(y, "y")
        return _flat_step((values - 0.2) / 0.3)

    def psi_o(self, y: Any) -> np.ndarray:
        values = _finite_array(y, "y")
        return 1.0 - _flat_step((values - 1.0) / 2.0)

    def f_o(self, y: Any) -> np.ndarray:
        return 1.0 - self.rho_o * self.psi_o(y)

    def max_terminal_log_slope(self) -> float:
        # The bound is only used as a construction guard.  A deterministic,
        # high-resolution screen is sufficient for this executable realization.
        y = np.linspace(0.0, 3.0, 8193)
        f = self.f_o(y)
        dy = y[1] - y[0]
        derivative = np.gradient(f, dy, edge_order=2)
        return float(np.max(np.maximum(derivative / f, 0.0)))

    def reference_tail_scales(self) -> dict[str, float]:
        """Return source-defined X_K/X_b and the explicit reference amplitude at X_K."""

        y_k = 0.2
        e_k = self.c_inf * self.X_K ** (-self.A) * float(self.f_o(y_k))
        return {"X_K": self.X_K, "X_b": self.X_b, "e_K": e_k}

    def _heat_minus_one_over_z(self, z: Any) -> np.ndarray:
        """Stable ``(Hcal(z)-1)/z`` including its exact one-sided z=0 value."""

        values = _finite_array(z, "z")
        if np.any(values < 0.0):
            raise ValueError("heat argument z must be nonnegative")
        heat = self._heat()
        out = np.empty_like(values)
        small = values <= 1.0e-4
        if np.any(~small):
            z_big = values[~small]
            out[~small] = (heat.heat_factor(z_big) - 1.0) / z_big
        if np.any(small):
            z_small = values[small]
            derivatives = [
                float(heat.heat_factor(np.asarray(0.0), derivative=k))
                for k in range(1, 5)
            ]
            out[small] = (
                derivatives[0]
                + 0.5 * derivatives[1] * z_small
                + derivatives[2] * z_small * z_small / 6.0
                + derivatives[3] * z_small * z_small * z_small / 24.0
            )
        return out

    def _scalar_discrepancy(self, eta: float) -> np.ndarray:
        if not math.isfinite(eta) or abs(eta) > 1.0:
            raise ValueError("eta must lie in [-1,1]")
        d = 1.0 - eta * eta
        if d == 0.0:
            return np.zeros(3, dtype=float)

        nodes, weights = leggauss(self.transition_quadrature_order)
        y = 1.5 * (nodes + 1.0)
        weights = 1.5 * weights
        X = self.X_tail * np.exp(y)
        z = 2.0 * d / X
        ratio = self._heat_minus_one_over_z(z)
        heat_minus_one = z * ratio
        multiplier = self.chi_K(y) * heat_minus_one

        E_cl = self.c_inf * np.power(X, -self.A) * self.f_o(y)
        delta_square = E_cl * E_cl * (2.0 * multiplier + multiplier * multiplier)
        delta_E = E_cl * multiplier

        transition = np.asarray(
            [
                np.sum(weights * 0.5 * delta_square),
                np.sum(weights * (-0.5) * delta_square * X),
                np.sum(weights * np.sqrt(2.0 * X) * delta_E * X),
            ],
            dtype=float,
        )

        # For y>=3, chi_K=f_o=1 exactly.  Write Hcal-1=z*R(z) and
        # integrate each exponential factor with Gauss-Laguerre.  This avoids
        # catastrophic cancellation and the very long O(1/h) I_sub tail.
        s, w = roots_laguerre(self.tail_quadrature_order)
        X0 = self.X_b
        z0 = 2.0 * d / X0

        def laguerre_R(rate: float) -> np.ndarray:
            return self._heat_minus_one_over_z(z0 * np.exp(-s / rate))

        k_cp_1 = 2.0 * self.A + 1.0
        R = laguerre_R(k_cp_1)
        tail_cp = (
            self.c_inf**2
            * d
            * X0 ** (-k_cp_1)
            / k_cp_1
            * np.sum(w * R)
        )
        k_cp_2 = 2.0 * self.A + 2.0
        R = laguerre_R(k_cp_2)
        tail_cp += (
            2.0
            * self.c_inf**2
            * d**2
            * X0 ** (-k_cp_2)
            / k_cp_2
            * np.sum(w * R * R)
        )

        k_s_1 = 1.0 + 2.0 * self.h
        R = laguerre_R(k_s_1)
        tail_s = (
            -2.0
            * self.c_inf**2
            * d
            * X0 ** (-k_s_1)
            / k_s_1
            * np.sum(w * R)
        )
        k_s_2 = 2.0 + 2.0 * self.h
        R = laguerre_R(k_s_2)
        tail_s += (
            -2.0
            * self.c_inf**2
            * d**2
            * X0 ** (-k_s_2)
            / k_s_2
            * np.sum(w * R * R)
        )

        R = laguerre_R(self.h)
        tail_i = (
            2.0
            * math.sqrt(2.0)
            * self.c_inf
            * d
            * X0 ** (-self.h)
            / self.h
            * np.sum(w * R)
        )
        return transition + np.asarray([tail_cp, tail_s, tail_i], dtype=float)

    def discrepancy(self, eta: Any) -> np.ndarray:
        """Return ``[...,3]`` physical ``(Delta C_p, Delta S, Delta I_sub)``."""

        values = _finite_array(eta, "eta")
        if np.any(np.abs(values) > 1.0):
            raise ValueError("eta must lie in [-1,1]")
        flat = values.reshape(-1)
        result = np.stack([self._scalar_discrepancy(float(v)) for v in flat], axis=0)
        return result.reshape(values.shape + (3,))

    def normalized_repair_target(
        self, eta: Any, *, X_star: float, e_star: float
    ) -> np.ndarray:
        """Return the source repair target that cancels the heat discrepancy."""

        X_scale = float(X_star)
        e_scale = float(e_star)
        if not math.isfinite(X_scale) or X_scale <= 0.0:
            raise ValueError("X_star must be positive and finite")
        if not math.isfinite(e_scale) or e_scale <= 0.0:
            raise ValueError("e_star must be positive and finite")
        scales = np.asarray(
            [e_scale**2, X_scale * e_scale**2, X_scale**1.5 * e_scale],
            dtype=float,
        )
        return -self.discrepancy(eta) / scales

    def _unsigned_payload(self) -> dict[str, Any]:
        return {
            "schema": SCHEMA,
            "provenance": {
                "repository": SOURCE_REPOSITORY,
                "commit": SOURCE_COMMIT,
                "path": SOURCE_PATH,
                "corrected_release": CORRECTED_RELEASE,
                "corrected_release_date": CORRECTED_RELEASE_DATE,
            },
            "source_formulas": dict(_SOURCE_FORMULAS),
            "parameters": {
                "h": self.h,
                "X_tail": self.X_tail,
                "c_inf": self.c_inf,
                "rho_o": self.rho_o,
                "heat_quadrature_order": self.heat_quadrature_order,
                "transition_quadrature_order": self.transition_quadrature_order,
                "tail_quadrature_order": self.tail_quadrature_order,
            },
            "autonomous_numerics": {
                "chi_K": "sigma((y-.2)/.3)",
                "default_X_tail": 1000.0,
                "default_c_inf": 1.0,
                "default_rho_o": 0.00025,
            },
            "truth_boundary": dict(_TRUTH_BOUNDARY),
        }

    @property
    def sha256(self) -> str:
        return hashlib.sha256(_canonical_json(self._unsigned_payload()).encode()).hexdigest()

    def to_payload(self) -> dict[str, Any]:
        payload = self._unsigned_payload()
        payload["sha256"] = self.sha256
        return payload

    @classmethod
    def from_payload(cls, payload: dict[str, Any]) -> "KokunoHeatReplacementDiscrepancy":
        if not isinstance(payload, dict) or payload.get("schema") != SCHEMA:
            raise ValueError("unexpected heat-replacement-discrepancy schema")
        expected_provenance = {
            "repository": SOURCE_REPOSITORY,
            "commit": SOURCE_COMMIT,
            "path": SOURCE_PATH,
            "corrected_release": CORRECTED_RELEASE,
            "corrected_release_date": CORRECTED_RELEASE_DATE,
        }
        if payload.get("provenance") != expected_provenance:
            raise ValueError("source provenance mismatch")
        if payload.get("source_formulas") != _SOURCE_FORMULAS:
            raise ValueError("source formula contract mismatch")
        if payload.get("truth_boundary") != _TRUTH_BOUNDARY:
            raise ValueError("truth boundary mismatch")
        params = payload.get("parameters")
        if not isinstance(params, dict):
            raise ValueError("parameters are missing")
        obj = cls(**params)
        if obj.to_payload() != payload:
            raise ValueError("heat replacement discrepancy payload hash or content mismatch")
        return obj

    def save_json(self, path: str | Path) -> Path:
        destination = Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(
            json.dumps(self.to_payload(), indent=2, sort_keys=True, allow_nan=False) + "\n",
            encoding="utf-8",
        )
        return destination

    @classmethod
    def load_json(cls, path: str | Path) -> "KokunoHeatReplacementDiscrepancy":
        return cls.from_payload(json.loads(Path(path).read_text(encoding="utf-8")))
