"""Cancellation-safe local-coordinate pressure API for selected PA.10 center.

This module is a narrow numerical interface layered on
:mod:`kokuno_pa10_selected_pressure_primitive`.  The corrected public Kokuno
reconstruction uses the selected stationary point ``eta_*`` and the very narrow
pressure layer generated by the repository-autonomous ``Lambda``.  Agent-4
cross-audit showed that an eta-only binary64 public API cannot support a strict
fundamental-theorem check once the natural layer width ``Lambda**(-1/2)`` is
comparable to only O(10^4) eta ulps.

The local coordinate

    s = sqrt(Lambda) * (eta - eta_*)

keeps the narrow layer O(1).  Values are evaluated directly in ``s`` without
first materializing ``eta_* + s/sqrt(Lambda)``.  The public source formulas are
unchanged.  In particular,

    d/deta = sqrt(Lambda) d/ds,
    p_eta = sqrt(Lambda) p_s.

The stationary-root polynomial factorization already introduced by Agent 1 is
re-expressed in the offset ``delta=s/sqrt(Lambda)``.  The local phase is then
integrated in ``s`` using

    d(log g)/ds = sqrt(Lambda) zeta_*(eta_* + s/sqrt(Lambda)).

This is a repository-selected numerical representation, not recovered hidden
Kokuno data and not a source radius-one-ball certificate.  Source M/K, B0/T_sh,
PA.16, global matched pressure, global leading velocity and PDE validation all
remain outside this module.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import copy
import hashlib
import json
import math
from pathlib import Path
from typing import Any

import numpy as np
from numpy.polynomial.legendre import leggauss

from .kokuno_pa10_selected_pressure_primitive import (
    CORRECTED_RELEASE,
    CORRECTED_RELEASE_DATE,
    SOURCE_COMMIT,
    SOURCE_PATH,
    SOURCE_REPOSITORY,
    KokunoPA10SelectedPressurePrimitive,
)


SCHEMA = "kokuno-pa10-local-pressure-coordinate-v1"
_LOCAL_PHASE_QUADRATURE_ORDER = 64
_LOCAL_NODES, _LOCAL_WEIGHTS = leggauss(_LOCAL_PHASE_QUADRATURE_ORDER)
_LOCAL_NODES = np.asarray(_LOCAL_NODES, dtype=float)
_LOCAL_WEIGHTS = np.asarray(_LOCAL_WEIGHTS, dtype=float)
_LOCAL_NODES.setflags(write=False)
_LOCAL_WEIGHTS.setflags(write=False)

_TRUTH_BOUNDARY = {
    "public_reconstruction_source": True,
    "selected_pressure_local_coordinate_executable": True,
    "selected_pressure_local_coordinate_chain_rule_executable": True,
    "selected_pressure_local_coordinate_selfcheck_executable": True,
    "selected_eta_two_term_compensated_mapping_executable": True,
    "selected_stationary_binary64_root_is_source_exact_hidden_value": False,
    "selected_local_coordinate_is_source_hidden_coordinate": False,
    "independent_agent4_local_coordinate_audit_required": True,
    "source_pressure_radius_one_ball_norm_machine_bound": False,
    "source_pressure_radius_one_ball_lipschitz_machine_bound": False,
    "source_R1_radius_one_ball_norm_machine_bound": False,
    "source_R2_radius_one_ball_norm_machine_bound": False,
    "source_operator_constant_M_machine_bound": False,
    "source_operator_constant_K_machine_bound": False,
    "source_B0_dependencies_machine_bound": False,
    "source_T_sh_lower_bound_verified": False,
    "selected_pa16_handoff_allowed": False,
    "global_pressure_matched": False,
    "global_leading_profile_reconstructed": False,
    "heldout_ns_residual_assessed": False,
    "pde_validated": False,
    "paper_exact": False,
    "openai_field_identified": False,
    "blowup_proved": False,
}


def _canonical_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), allow_nan=False)


def _finite_array(value: Any, name: str) -> np.ndarray:
    out = np.asarray(value, dtype=float)
    if not np.all(np.isfinite(out)):
        raise ValueError(f"{name} must contain only finite values")
    return out


def _relative_rms(error: np.ndarray, reference: np.ndarray) -> float:
    err = np.asarray(error, dtype=float)
    ref = np.asarray(reference, dtype=float)
    denominator = max(float(np.sqrt(np.mean(ref * ref))), 1.0e-300)
    return float(np.sqrt(np.mean(err * err)) / denominator)


def _relative_max(error: np.ndarray, reference: np.ndarray) -> float:
    err = np.asarray(error, dtype=float)
    ref = np.asarray(reference, dtype=float)
    denominator = max(float(np.max(np.abs(ref))), 1.0e-300)
    return float(np.max(np.abs(err)) / denominator)


@dataclass(frozen=True)
class KokunoPA10LocalPressureCoordinate:
    """Selected-center pressure primitive evaluated directly in local ``s``."""

    primitive: KokunoPA10SelectedPressurePrimitive = field(
        default_factory=KokunoPA10SelectedPressurePrimitive
    )
    radial_quadrature_points: int = 64

    _radial_nodes: np.ndarray = field(init=False, repr=False, compare=False)
    _radial_weights: np.ndarray = field(init=False, repr=False, compare=False)

    def __post_init__(self) -> None:
        if not isinstance(self.primitive, KokunoPA10SelectedPressurePrimitive):
            raise TypeError("primitive must be a KokunoPA10SelectedPressurePrimitive")
        if isinstance(self.radial_quadrature_points, bool) or not isinstance(
            self.radial_quadrature_points, (int, np.integer)
        ):
            raise TypeError("radial_quadrature_points must be an integer")
        order = int(self.radial_quadrature_points)
        if not 16 <= order <= 128:
            raise ValueError("radial_quadrature_points must lie in [16,128]")
        nodes, weights = leggauss(order)
        nodes = np.asarray(nodes, dtype=float)
        weights = np.asarray(weights, dtype=float)
        nodes.setflags(write=False)
        weights.setflags(write=False)
        object.__setattr__(self, "radial_quadrature_points", order)
        object.__setattr__(self, "_radial_nodes", nodes)
        object.__setattr__(self, "_radial_weights", weights)

    @property
    def core(self):
        return self.primitive.core

    @property
    def sqrt_lambda(self) -> float:
        return math.sqrt(float(self.core.rescaling_lambda))

    @property
    def eta_star(self) -> float:
        return float(self.core.phase_stationary_eta)

    @property
    def layer_width(self) -> float:
        return 1.0 / self.sqrt_lambda

    def eta_offset(self, s: Any) -> np.ndarray:
        """Return ``delta=eta-eta_*`` without adding it to ``eta_*``."""

        values = _finite_array(s, "s")
        delta = values / self.sqrt_lambda
        room = 1.0 - abs(self.eta_star)
        if np.any(np.abs(delta) > room):
            raise ValueError("local coordinate maps outside |eta|<=1")
        return delta

    def eta_two_term(self, s: Any) -> tuple[np.ndarray, np.ndarray]:
        """Return a two-float representation ``eta_hi + eta_lo``.

        Downstream code that truly requires physical eta can retain the low
        component instead of silently discarding the narrow-layer offset.
        Local pressure evaluation itself never needs this materialization.
        """

        delta = self.eta_offset(s)
        root = self.eta_star
        hi = root + delta
        bp = hi - root
        ap = hi - bp
        br = delta - bp
        ar = root - ap
        lo = ar + br
        return np.asarray(hi, dtype=float), np.asarray(lo, dtype=float)

    def _local_axis_state(self, s: Any) -> dict[str, np.ndarray]:
        s_values = _finite_array(s, "s")
        delta = self.eta_offset(s_values)
        r = self.eta_star
        a = -4.0
        b = -float(self.core.j0)
        c = float(self.core.D) + 4.0

        hprime_r = 3.0 * a * r * r + 2.0 * b * r + c
        q1 = 3.0 * a * r + b
        H = delta * (hprime_r + q1 * delta + a * delta * delta)
        H_eta = hprime_r + 2.0 * q1 * delta + 3.0 * a * delta * delta

        eta_sq = r * r + 2.0 * r * delta + delta * delta
        L = 1.0 - 2.0 * float(self.core.h) * eta_sq
        sigma2 = float(self.core.sigma_star) ** 2
        denominator = H * H + sigma2
        chi = H * H / denominator
        chi_eta = 2.0 * H * H_eta * sigma2 / (denominator * denominator)
        chi_s = chi_eta / self.sqrt_lambda
        zeta = -L * H / denominator
        log_g_s = self.sqrt_lambda * zeta
        return {
            "delta": delta,
            "H_star": H,
            "H_star_eta": H_eta,
            "L": L,
            "chi": chi,
            "chi_eta": chi_eta,
            "chi_s": chi_s,
            "zeta_star": zeta,
            "log_g_s": log_g_s,
        }

    def _local_log_g(self, s: Any) -> np.ndarray:
        values = _finite_array(s, "s")
        flat = values.reshape(-1)
        out = np.empty_like(flat)
        for index, upper in enumerate(flat):
            upper_value = float(upper)
            if upper_value == 0.0:
                out[index] = 0.0
                continue
            half = 0.5 * upper_value
            midpoint = half
            points = midpoint + half * _LOCAL_NODES
            integrand = self._local_axis_state(points)["log_g_s"]
            out[index] = half * float(np.dot(_LOCAL_WEIGHTS, integrand))
        raw = out.reshape(values.shape)
        return np.minimum(raw, 0.0)

    def _radial_integrals(
        self,
        Y: np.ndarray,
        chi: np.ndarray,
        chi_s: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray]:
        flat_Y = np.asarray(Y, dtype=float).reshape(-1)
        flat_chi = np.asarray(chi, dtype=float).reshape(-1)
        flat_chi_s = np.asarray(chi_s, dtype=float).reshape(-1)
        I = np.empty_like(flat_Y)
        I_s = np.empty_like(flat_Y)
        for index, (upper, local_chi, local_chi_s) in enumerate(
            zip(flat_Y, flat_chi, flat_chi_s, strict=True)
        ):
            if upper == 0.0:
                I[index] = 0.0
                I_s[index] = 0.0
                continue
            v = 0.5 * upper * (self._radial_nodes + 1.0)
            phi = self.core.f0(v * local_chi)
            phi_prime = self.core.f0_prime(v * local_chi)
            scale = 0.5 * upper
            I[index] = scale * float(np.dot(self._radial_weights, phi * phi))
            integrand_s = 2.0 * phi * phi_prime * v * local_chi_s
            I_s[index] = scale * float(np.dot(self._radial_weights, integrand_s))
        return I.reshape(np.shape(Y)), I_s.reshape(np.shape(Y))

    def evaluate_local(self, Y: Any, s: Any) -> dict[str, np.ndarray]:
        """Evaluate the selected pressure/profile primitive directly in ``s``."""

        Y_array, s_array = np.broadcast_arrays(
            _finite_array(Y, "Y"), _finite_array(s, "s")
        )
        if np.any((Y_array < 0.0) | (Y_array > 4.1)):
            raise ValueError("source contraction-center domain requires 0<=Y<=4.1")
        state = self._local_axis_state(s_array)
        log_g = self._local_log_g(s_array)
        with np.errstate(under="ignore"):
            g = np.exp(log_g)

        arg = Y_array * state["chi"]
        Phi = self.core.f0(arg)
        Phi_prime = self.core.f0_prime(arg)
        Y_Phi_Y = Y_array * state["chi"] * Phi_prime
        Phi_s = Y_array * state["chi_s"] * Phi_prime
        Phi_eta = self.sqrt_lambda * Phi_s

        I, I_s = self._radial_integrals(Y_array, state["chi"], state["chi_s"])
        g2 = g * g
        p = g2 * I
        p_Y = g2 * Phi * Phi
        Y_p_Y = Y_array * p_Y
        p_s = g2 * (2.0 * state["log_g_s"] * I + I_s)
        p_eta = self.sqrt_lambda * p_s
        eta_hi, eta_lo = self.eta_two_term(s_array)

        result = {
            "Y": Y_array,
            "s": s_array,
            "eta_offset": state["delta"],
            "eta_hi": eta_hi,
            "eta_lo": eta_lo,
            "Phi": Phi,
            "Phi_s": Phi_s,
            "Phi_eta": Phi_eta,
            "Y_Phi_Y": Y_Phi_Y,
            "log_g": log_g,
            "log_g_s": state["log_g_s"],
            "g": g,
            "chi": state["chi"],
            "chi_s": state["chi_s"],
            "zeta_star_local": state["zeta_star"],
            "pressure_integral_I": I,
            "pressure_integral_I_s": I_s,
            "p": p,
            "p_Y": p_Y,
            "Y_p_Y": Y_p_Y,
            "p_s": p_s,
            "p_eta": p_eta,
        }
        if not all(np.all(np.isfinite(value)) for value in result.values()):
            raise OverflowError("local pressure coordinate produced non-finite values")
        return result

    __call__ = evaluate_local

    def diagnostic_receipt(self) -> dict[str, Any]:
        """Deterministic Agent-1 self-check; not independent PDE validation."""

        Y = np.asarray([0.7, 1.2, 1.9, 2.6, 3.2, 3.8], dtype=float)
        s = np.asarray([-0.83, -0.51, -0.19, 0.14, 0.43, 0.79], dtype=float)
        reference = self.evaluate_local(Y, s)

        fd_steps = (0.04, 0.02, 0.01)
        fd_rms: list[float] = []
        fd_max: list[float] = []
        for step in fd_steps:
            fm3 = self.evaluate_local(Y, s - 3.0 * step)["p"]
            fm2 = self.evaluate_local(Y, s - 2.0 * step)["p"]
            fm1 = self.evaluate_local(Y, s - step)["p"]
            fp1 = self.evaluate_local(Y, s + step)["p"]
            fp2 = self.evaluate_local(Y, s + 2.0 * step)["p"]
            fp3 = self.evaluate_local(Y, s + 3.0 * step)["p"]
            derivative = (
                -fm3 + 9.0 * fm2 - 45.0 * fm1 + 45.0 * fp1 - 9.0 * fp2 + fp3
            ) / (60.0 * step)
            error = derivative - reference["p_s"]
            fd_rms.append(_relative_rms(error, reference["p_s"]))
            fd_max.append(_relative_max(error, reference["p_s"]))

        intervals = ((-0.91, 0.31), (-0.62, 0.77), (-0.23, 0.94))
        ft_Y = np.asarray([0.9, 2.1, 3.7], dtype=float)
        ft_orders = (16, 32, 64)
        ft_rms: list[float] = []
        ft_max: list[float] = []
        for order in ft_orders:
            nodes, weights = leggauss(order)
            errors = []
            references = []
            for y_value, (left, right) in zip(ft_Y, intervals, strict=True):
                half = 0.5 * (right - left)
                midpoint = 0.5 * (right + left)
                points = midpoint + half * nodes
                integral = half * float(
                    np.dot(weights, self.evaluate_local(y_value, points)["p_s"])
                )
                endpoint = float(
                    self.evaluate_local(y_value, right)["p"]
                    - self.evaluate_local(y_value, left)["p"]
                )
                errors.append(integral - endpoint)
                references.append(endpoint)
            ft_rms.append(
                _relative_rms(np.asarray(errors), np.asarray(references))
            )
            ft_max.append(
                _relative_max(np.asarray(errors), np.asarray(references))
            )

        chain = reference["p_eta"] - self.sqrt_lambda * reference["p_s"]
        hi, lo = self.eta_two_term(s)
        recovered_delta = (hi - self.eta_star) + lo
        mapping_error = recovered_delta - self.eta_offset(s)

        fd_refinement = [
            fd_rms[index] / fd_rms[index + 1] if fd_rms[index + 1] > 0.0 else math.inf
            for index in range(len(fd_rms) - 1)
        ]
        passed = bool(
            fd_rms[-1] <= 2.0e-5
            and fd_max[-1] <= 5.0e-5
            and min(fd_refinement) >= 8.0
            and ft_rms[-1] <= 1.0e-8
            and ft_max[-1] <= 5.0e-8
            and float(np.max(np.abs(chain))) == 0.0
            and float(np.max(np.abs(reference["p_s"]))) > 1.0e-8
        )
        return {
            "schema": "kokuno-pa10-local-pressure-coordinate-selfcheck-v1",
            "candidate_sha256": self.sha256,
            "source": self.source_metadata,
            "selected": {
                "Lambda": float(self.core.rescaling_lambda),
                "sqrt_Lambda": self.sqrt_lambda,
                "eta_star": self.eta_star,
                "layer_width": self.layer_width,
                "eta_ulp_at_star": float(np.spacing(self.eta_star)),
                "eta_ulp_over_layer_width": abs(float(np.spacing(self.eta_star))) / self.layer_width,
            },
            "fd6_local_p_s": {
                "steps": list(fd_steps),
                "relative_rms": fd_rms,
                "relative_max": fd_max,
                "rms_refinement_ratios": fd_refinement,
                "finest_rms_gate": 2.0e-5,
                "finest_max_gate": 5.0e-5,
                "refinement_gate": 8.0,
            },
            "local_s_fundamental_theorem": {
                "orders": list(ft_orders),
                "relative_rms": ft_rms,
                "relative_max": ft_max,
                "finest_rms_gate": 1.0e-8,
                "finest_max_gate": 5.0e-8,
            },
            "chain_rule_max_abs_error": float(np.max(np.abs(chain))),
            "two_term_eta_mapping_max_abs_offset_error": float(
                np.max(np.abs(mapping_error))
            ),
            "local_p_s_rms": float(np.sqrt(np.mean(reference["p_s"] ** 2))),
            "selfcheck_passed": passed,
            "independent_agent4_audit": "required",
            "heldout_ns_residual_assessed": False,
            "pde_validated": False,
        }

    @property
    def source_metadata(self) -> dict[str, Any]:
        return {
            "repository": SOURCE_REPOSITORY,
            "commit": SOURCE_COMMIT,
            "path": SOURCE_PATH,
            "corrected_release": CORRECTED_RELEASE,
            "corrected_release_date": CORRECTED_RELEASE_DATE,
            "source_formulas": [
                "s=sqrt(Lambda)*(eta-eta_*)",
                "d/deta=sqrt(Lambda)*d/ds",
                "p_eta=sqrt(Lambda)*p_s",
                "d(log g)/ds=sqrt(Lambda)*zeta_*",
            ],
            "representation_note": (
                "s is a repository-selected cancellation-safe numerical coordinate; "
                "it is not claimed to be a recovered hidden source coordinate"
            ),
        }

    @property
    def truth_boundary(self) -> dict[str, bool]:
        return copy.deepcopy(_TRUTH_BOUNDARY)

    def to_payload(self) -> dict[str, Any]:
        payload = {
            "schema": SCHEMA,
            "source": self.source_metadata,
            "numerics": {
                "radial_quadrature_points": self.radial_quadrature_points,
                "local_phase_quadrature_points": _LOCAL_PHASE_QUADRATURE_ORDER,
                "local_coordinate": "s=sqrt(Lambda)*(eta-eta_*)",
                "eta_materialization": "two-term compensated pair available",
            },
            "selected": {
                "Lambda": float(self.core.rescaling_lambda),
                "eta_star": self.eta_star,
                "underlying_pressure_primitive_sha256": self.primitive.sha256,
            },
            "truth_boundary": self.truth_boundary,
        }
        digest = hashlib.sha256(_canonical_json(payload).encode("utf-8")).hexdigest()
        return {**payload, "sha256": digest}

    @property
    def sha256(self) -> str:
        return str(self.to_payload()["sha256"])

    def save(self, path: str | Path) -> None:
        destination = Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(
            json.dumps(self.to_payload(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    @classmethod
    def from_payload(cls, payload: dict[str, Any]) -> "KokunoPA10LocalPressureCoordinate":
        data = copy.deepcopy(payload)
        if data.get("schema") != SCHEMA:
            raise ValueError("unsupported local pressure-coordinate schema")
        claimed = data.pop("sha256", None)
        actual = hashlib.sha256(_canonical_json(data).encode("utf-8")).hexdigest()
        if claimed != actual:
            raise ValueError("local pressure-coordinate payload SHA mismatch")
        if data.get("truth_boundary") != _TRUTH_BOUNDARY:
            raise ValueError("local pressure-coordinate truth-boundary mismatch")
        numerics = data.get("numerics", {})
        result = cls(radial_quadrature_points=int(numerics["radial_quadrature_points"]))
        if result.to_payload() != payload:
            raise ValueError("local pressure-coordinate payload does not replay selected state")
        return result

    @classmethod
    def load(cls, path: str | Path) -> "KokunoPA10LocalPressureCoordinate":
        return cls.from_payload(json.loads(Path(path).read_text(encoding="utf-8")))


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    interface = KokunoPA10LocalPressureCoordinate()
    receipt = interface.diagnostic_receipt()
    if not receipt["selfcheck_passed"]:
        raise SystemExit("local pressure-coordinate self-check failed")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(receipt, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
