"""Carrier-resolved autonomous Kokuno-structured public oscillatory candidate.

This is one repository-autonomous reparameterization of Agent-2's already
source-formula-bound public complete-curl pipeline.  It exists because Agent 4's
frozen black-box Cartesian FD4 audit resolved the project support after #539 but
still under-resolved the public carrier: the old autonomous background generated
large angular winding numbers even though the field is assembled through exact
vector-potential curls.

The source-displayed phase, carrier rounding, complete-curl, signed covariance,
partition, Q/epsilon schedule and physical scaling are unchanged.  Only the
repository-autonomous constant background realization is replaced by one bounded
choice that lowers the effective physical carrier frequencies.  This module
therefore does NOT claim Kokuno's unpublished positive-order background and does
NOT claim that the independent divergence audit passes until Agent 4 reruns the
unchanged protocol.
"""
from __future__ import annotations

from functools import lru_cache
import math
from pathlib import Path
from typing import Any

import numpy as np

from .kokuno_public_candidate_velocity import KokunoPublicCandidateOscillatoryVelocity

SCHEMA = "kokuno-public-carrier-resolved-oscillatory-velocity-v1"
PARENT_AGENT2_HEAD = "985d1c3fc43081d2d87feb1f0c27643cc4ebe75b"

# Repository-autonomous, source-compatible constants.  They are deliberately
# finite and frozen rather than exposed as another free optimization vector.
# R0 stays aligned with the public annulus.  F0, a and u_star are changed only
# to reduce the source carrier generated by the same displayed phase equations.
_CARRIER_RESOLVED_BACKGROUND = {
    "R0": 0.82,
    "F0": 16.0,
    "a": 64.0,
    "b_s": 0.20,
    "u_star": 8.0,
    "F": 16.0,
    "G": 0.24,
    "F_R": 0.0,
    "G_R": 0.0,
    "F_Z": 0.0,
    "G_Z": 0.0,
}

# Declared autonomous design box used only as provenance for the frozen choice.
# Nothing here is source-recovered.
_AUTONOMOUS_BACKGROUND_BOUNDS = {
    "R0": (0.70, 0.90),
    "F0": (1.0, 16.0),
    "a": (2.1, 64.0),
    "b_s": (0.0, 0.30),
    "u_star": (0.5, 8.0),
    "F": (1.0, 16.0),
    "G": (0.0, 0.50),
}

# These steps/radius reproduce only the *resolution scale* of the frozen Agent-4
# black-box protocol.  No derivative or divergence from Agent 4 is copied or
# used as an oracle here.
FD4_RESOLUTION_STEPS = (0.02, 0.01, 0.005)
FD4_REFERENCE_RADIUS = 0.42


def _background_arrays(field: KokunoPublicCandidateOscillatoryVelocity) -> dict[str, np.ndarray]:
    """Return the field's current constant background arrays."""
    background = field._background()  # Agent-2-owned public candidate internals.
    out: dict[str, np.ndarray] = {}
    for key, value in background.items():
        arr = np.asarray(value, dtype=float)
        if arr.shape != (len(field.beta_labels),) or not np.all(np.isfinite(arr)):
            raise ValueError(f"background {key} must be finite with one value per beta")
        out[key] = arr
    return out


def carrier_resolution_diagnostics(
    field: KokunoPublicCandidateOscillatoryVelocity,
    *,
    reference_radius: float = FD4_REFERENCE_RADIUS,
    fd4_steps: tuple[float, ...] = FD4_RESOLUTION_STEPS,
) -> dict[str, Any]:
    """Quantify physical carrier scales without differentiating the public field.

    For ``exp(i*k*Phi)`` the local public-coordinate phase wavenumbers for the
    frozen constant-background realization are

        radial      = k*x0,
        tangential  = (k*p)/R = kp/R,
        axial       = k*p_z/epsilon.

    This is a source-formula-derived resolution diagnostic, not an independent
    divergence test.  Agent 4 remains the owner of the black-box FD4 verdict.
    """
    radius = float(reference_radius)
    if not math.isfinite(radius) or radius <= 0.0:
        raise ValueError("reference_radius must be positive and finite")
    steps = tuple(float(step) for step in fd4_steps)
    if not steps or any((not math.isfinite(step)) or step <= 0.0 for step in steps):
        raise ValueError("fd4_steps must be nonempty positive finite values")

    labels = field.beta_labels
    n_beta = len(labels)
    geometry = field._static["geometry"]
    L_s = np.asarray(geometry["L_s_by_beta"], dtype=float)
    epsilon = np.asarray(geometry["epsilon_by_beta"], dtype=float)
    if L_s.shape != (n_beta,) or epsilon.shape != (n_beta,):
        raise RuntimeError("autonomous geometry lost one-value-per-beta band scales")

    background = _background_arrays(field)
    v = np.stack((0.25 * L_s, 0.75 * L_s), axis=-1)
    frame = field.bridge.phase_family.phase_frame(
        R=np.full(n_beta, radius),
        Z=np.zeros(n_beta),
        theta=np.asarray(0.0),
        v=v,
        beta_labels=labels,
        L_s=L_s,
        **background,
    )

    k = np.asarray(frame["k_by_beta"], dtype=float)
    kp = np.asarray(frame["kp_by_beta_sign"], dtype=float)
    pz = np.asarray(frame["p_z_by_beta_sign"], dtype=float)
    x0 = np.asarray(frame["x0_by_beta_sign"], dtype=float)
    radial = k[:, None] * x0
    tangential = kp / radius
    axial = k[:, None] * pz / epsilon[:, None]
    norm = np.sqrt(radial * radial + tangential * tangential + axial * axial)
    wavelength = 2.0 * math.pi / np.maximum(norm, np.finfo(float).tiny)

    phase_increments = {
        f"{step:.6g}": {
            "max_local_phase_increment": float(step * np.max(norm)),
            "max_tangential_phase_increment": float(step * np.max(np.abs(tangential))),
            "max_axial_phase_increment": float(step * np.max(np.abs(axial))),
            "max_radial_phase_increment": float(step * np.max(np.abs(radial))),
        }
        for step in steps
    }

    return {
        "reference_radius": radius,
        "beta_labels": labels,
        "sign_labels": ("sigma_plus", "sigma_minus"),
        "kp_by_beta_sign": kp.astype(np.int64),
        "radial_wavenumber_by_beta_sign": radial,
        "tangential_wavenumber_by_beta_sign": tangential,
        "axial_wavenumber_by_beta_sign": axial,
        "local_wavenumber_norm_by_beta_sign": norm,
        "local_wavelength_by_beta_sign": wavelength,
        "max_abs_kp": int(np.max(np.abs(kp))),
        "max_local_wavenumber": float(np.max(norm)),
        "minimum_local_wavelength": float(np.min(wavelength)),
        "phase_increments_by_step": phase_increments,
        "source_phase_formula_bound": True,
        "independent_fd4_divergence_assessed": False,
    }


class KokunoCarrierResolvedCandidateOscillatoryVelocity(KokunoPublicCandidateOscillatoryVelocity):
    """Public complete-curl candidate with one frozen carrier-resolved background."""

    def _background(self) -> dict[str, Any]:
        n = len(self.beta_labels)
        return {
            key: np.full(n, float(value))
            for key, value in _CARRIER_RESOLVED_BACKGROUND.items()
        }

    def carrier_resolution_receipt(self) -> dict[str, Any]:
        diagnostic = carrier_resolution_diagnostics(self)
        return {
            "schema": "kokuno-public-carrier-resolution-diagnostic-v1",
            "background_binding": "repository_autonomous_bounded_carrier_resolution_reparameterization",
            "selected_background": dict(_CARRIER_RESOLVED_BACKGROUND),
            "declared_autonomous_bounds": {
                key: [float(bounds[0]), float(bounds[1])]
                for key, bounds in _AUTONOMOUS_BACKGROUND_BOUNDS.items()
            },
            "diagnostic": {
                "reference_radius": diagnostic["reference_radius"],
                "max_abs_kp": diagnostic["max_abs_kp"],
                "max_local_wavenumber": diagnostic["max_local_wavenumber"],
                "minimum_local_wavelength": diagnostic["minimum_local_wavelength"],
                "phase_increments_by_step": diagnostic["phase_increments_by_step"],
            },
            "source_formulas_changed": False,
            "vector_potential_complete_curl_path_changed": False,
            "independent_agent4_reaudit_required": True,
            "pde_validated": False,
            "paper_exact": False,
        }

    def to_payload(self) -> dict[str, Any]:
        payload = super().to_payload()
        payload["schema"] = SCHEMA
        payload["parent_agent2_head"] = PARENT_AGENT2_HEAD
        autonomous = dict(payload["autonomous_choices"])
        autonomous["background"] = (
            "bounded repository-autonomous carrier-resolution background; "
            "not Kokuno's unpublished positive-order background"
        )
        payload["autonomous_choices"] = autonomous
        payload["frozen_realization"]["background"] = dict(_CARRIER_RESOLVED_BACKGROUND)
        payload["frozen_realization"]["carrier_resolution"] = self.carrier_resolution_receipt()
        truth = dict(payload["truth_boundary"])
        truth.update(
            {
                "candidate_carrier_resolution_reparameterized": True,
                "candidate_carrier_scales_quantified": True,
                "independent_fd4_divergence_reaudit_required": True,
                "independent_fd4_divergence_passed": False,
                "actual_positive_order_background_bound": False,
                "formal_full_domain_pde_gate_assessed": False,
                "pde_validated": False,
                "paper_exact": False,
            }
        )
        payload["truth_boundary"] = truth
        return payload


@lru_cache(maxsize=1)
def default_field() -> KokunoCarrierResolvedCandidateOscillatoryVelocity:
    return KokunoCarrierResolvedCandidateOscillatoryVelocity()


def velocity_osc(x: Any, y: Any, z: Any, t: Any) -> np.ndarray:
    """Return the carrier-resolved public candidate correction as ``[...,3]``."""
    return default_field().velocity_osc(x, y, z, t)
