"""Real-defect phase-mean projector for Kokuno-style mean correction work.

This module deliberately does not invent a surrogate residual.  It evaluates the
repository's independent finite-difference momentum operator on an actual public
velocity callable, repeats that evaluation for uniformly shifted phases of the
Agent-2 complete-curl correction, and extracts the zero-harmonic defect increment.

KokunoYumeto's corrected 2026-09-09 reader keeps the full wave covariance
``W^{ab}=<w_a w_b>`` in the mean momentum equations (MC11--MC12).  The source
mean is an angular/auxiliary mean tied to its cylindrical construction.  Our
Agent-2 correction uses an autonomous Cartesian affine phase instead, so the
uniform phase-shift average here is an engineering adapter, not a paper-exact
implementation of the source mean operator.

For a fixed pressure/force model, subtracting the base momentum operator from the
phase-averaged composite operator cancels those unchanged terms.  Because the
complete-curl correction has zero phase mean, the surviving increment is the
quadratic zero harmonic generated by the real public velocity field.  This is the
typed input intended for later mean/radial correction machinery.
"""
from __future__ import annotations

from dataclasses import dataclass, replace
import argparse
import json
from math import pi
from pathlib import Path
from typing import Callable

import numpy as np

from .constrained_validation import residual
from .kokuno_complete_curl import KokunoCompleteCurlCorrection


PointVelocity = Callable[[np.ndarray, float], np.ndarray]


def _zero_pressure(points: np.ndarray, time: float) -> np.ndarray:
    del time
    return np.zeros(len(points), dtype=float)


def _zero_force(points: np.ndarray, time: float) -> np.ndarray:
    del time
    return np.zeros_like(points, dtype=float)


def _wrap_phase(value: float) -> float:
    wrapped = (float(value) + pi) % (2.0 * pi) - pi
    # Keep +pi represented as +pi when the input was exactly there; either value
    # is physically identical, but the correction's documented bound is closed.
    if wrapped == -pi and value > 0:
        return pi
    return wrapped


def _vector_rms(values: np.ndarray) -> float:
    values = np.asarray(values, dtype=float)
    return float(np.sqrt(np.mean(np.sum(values * values, axis=-1))))


def _vector_max(values: np.ndarray) -> float:
    values = np.asarray(values, dtype=float)
    return float(np.max(np.linalg.norm(values, axis=-1)))


def cylindrical_theta_component(vectors: np.ndarray, points: np.ndarray, *, axis_tol: float = 1.0e-10) -> np.ndarray:
    """Project Cartesian vectors onto e_theta; reject points too close to the axis."""
    vectors = np.asarray(vectors, dtype=float)
    points = np.asarray(points, dtype=float)
    if points.ndim != 2 or points.shape[1] != 3 or vectors.shape != points.shape:
        raise ValueError("vectors and points must both be finite (N,3) arrays")
    if not np.isfinite(points).all() or not np.isfinite(vectors).all():
        raise ValueError("vectors and points must be finite")
    radius = np.hypot(points[:, 0], points[:, 1])
    if np.any(radius <= axis_tol):
        raise ValueError("theta projection is undefined on the cylindrical axis")
    e_theta = np.column_stack((-points[:, 1] / radius, points[:, 0] / radius, np.zeros(len(points))))
    return np.einsum("ni,ni->n", vectors, e_theta)


@dataclass(frozen=True)
class PhaseMeanDefectSample:
    """Typed real-operator sample returned by :class:`PhaseMeanDefectContract`."""

    points: np.ndarray
    time: float
    phases: np.ndarray
    base_momentum: np.ndarray
    phase_momentum: np.ndarray
    phase_divergence: np.ndarray

    @property
    def mean_momentum(self) -> np.ndarray:
        return np.mean(self.phase_momentum, axis=0)

    @property
    def mean_defect_increment(self) -> np.ndarray:
        return self.mean_momentum - self.base_momentum

    @property
    def nonzero_phase_remainder(self) -> np.ndarray:
        return self.phase_momentum - self.mean_momentum[None, :, :]

    def metrics(self) -> dict[str, float]:
        increment = self.mean_defect_increment
        theta = cylindrical_theta_component(increment, self.points)
        remainder = self.nonzero_phase_remainder
        mean_rms = _vector_rms(self.mean_momentum)
        return {
            "base_operator_rms": _vector_rms(self.base_momentum),
            "mean_composite_operator_rms": mean_rms,
            "mean_defect_increment_rms": _vector_rms(increment),
            "mean_defect_increment_max": _vector_max(increment),
            "theta_mean_defect_rms": float(np.sqrt(np.mean(theta * theta))),
            "theta_mean_defect_max": float(np.max(np.abs(theta))),
            "nonzero_phase_remainder_rms": float(np.sqrt(np.mean(np.sum(remainder * remainder, axis=-1)))),
            "composite_divergence_phase_max": float(np.max(np.abs(self.phase_divergence))),
            "mean_defect_over_mean_operator_rms": _vector_rms(increment) / max(mean_rms, np.finfo(float).tiny),
        }


@dataclass(frozen=True)
class PhaseMeanDefectContract:
    """Independent real-defect contract for one complete-curl correction.

    ``base_velocity`` must consume ``(N,3)`` Cartesian points and a scalar time.
    The correction is evaluated through its public ``at_points`` method.  The
    underlying momentum operator is ``constrained_validation.residual`` and is
    therefore separate from any fitting/training loss.
    """

    nu: float = 0.01
    step: float = 0.005
    time_bounds: tuple[float, float] = (0.25, 0.75)
    phase_count: int = 8

    def __post_init__(self) -> None:
        if not np.isfinite([self.nu, self.step, *self.time_bounds]).all():
            raise ValueError("contract scalars must be finite")
        if self.nu <= 0.0 or self.step <= 0.0:
            raise ValueError("nu and step must be positive")
        if self.time_bounds[0] >= self.time_bounds[1]:
            raise ValueError("time_bounds must be increasing")
        if self.phase_count < 4 or self.phase_count % 2:
            raise ValueError("phase_count must be an even integer >= 4")

    def evaluate(
        self,
        base_velocity: PointVelocity,
        correction: KokunoCompleteCurlCorrection,
        points: np.ndarray,
        time: float,
    ) -> PhaseMeanDefectSample:
        if not callable(base_velocity):
            raise TypeError("base_velocity must be a callable public velocity evaluator")
        if not isinstance(correction, KokunoCompleteCurlCorrection):
            raise TypeError("correction must be KokunoCompleteCurlCorrection")
        points = np.asarray(points, dtype=float)
        if points.ndim != 2 or points.shape[1] != 3 or not np.isfinite(points).all() or len(points) == 0:
            raise ValueError("points must be a nonempty finite (N,3) array")
        if not np.isfinite(time) or not self.time_bounds[0] <= time <= self.time_bounds[1]:
            raise ValueError("time must lie in the contract time interval")

        base = residual(
            base_velocity,
            _zero_pressure,
            _zero_force,
            points,
            float(time),
            nu=self.nu,
            step=self.step,
            time_bounds=self.time_bounds,
        )

        shifts = 2.0 * pi * np.arange(self.phase_count, dtype=float) / self.phase_count
        momenta: list[np.ndarray] = []
        divergences: list[np.ndarray] = []
        for shift in shifts:
            shifted = replace(correction, phase=_wrap_phase(correction.phase + float(shift)))

            def composite_velocity(x: np.ndarray, t: float, shifted=shifted) -> np.ndarray:
                base_values = np.asarray(base_velocity(x, t), dtype=float)
                delta = shifted.at_points(x, t)
                if base_values.shape != delta.shape or base_values.shape != x.shape:
                    raise ValueError("base and correction must return (N,3) Cartesian velocities")
                return base_values + delta

            result = residual(
                composite_velocity,
                _zero_pressure,
                _zero_force,
                points,
                float(time),
                nu=self.nu,
                step=self.step,
                time_bounds=self.time_bounds,
            )
            momenta.append(np.asarray(result["momentum"], dtype=float))
            divergences.append(np.asarray(result["divergence"], dtype=float))

        return PhaseMeanDefectSample(
            points=points.copy(),
            time=float(time),
            phases=shifts,
            base_momentum=np.asarray(base["momentum"], dtype=float),
            phase_momentum=np.stack(momenta, axis=0),
            phase_divergence=np.stack(divergences, axis=0),
        )


def _held_out_points(correction: KokunoCompleteCurlCorrection, *, seed: int, count: int) -> np.ndarray:
    """Deterministic interior support sample, kept away from the cylindrical axis."""
    if count <= 0:
        raise ValueError("count must be positive")
    center = np.asarray(correction.center, dtype=float)
    widths = np.asarray(correction.half_widths, dtype=float)
    lo = center - 0.82 * widths
    hi = center + 0.82 * widths
    rng = np.random.default_rng(seed)
    chunks: list[np.ndarray] = []
    have = 0
    while have < count:
        draw = rng.uniform(lo, hi, size=(max(2 * (count - have), 32), 3))
        draw = draw[np.hypot(draw[:, 0], draw[:, 1]) > 0.12]
        if len(draw):
            chunks.append(draw)
            have += len(draw)
    return np.concatenate(chunks, axis=0)[:count]


def generate_current_candidate_report(
    *,
    candidate_path: str | Path = "artifacts/bipolar_joint_capped/candidate.json",
    output: str | Path = "artifacts/kokuno_agent3/mean_defect_report.json",
    seed: int = 9172703,
    point_count: int = 128,
) -> dict:
    """Evaluate the typed mean defect on the current capped bipolar artifact.

    This is a diagnostic of the *increment* created by Agent-2's correction.
    It is not a full pressure/force fit and does not assess the 1e-3 PDE gate.
    """
    from .constrained_eq45_supported_candidate import Eq45SupportedVelocityCandidate

    candidate_path = Path(candidate_path)
    candidate = Eq45SupportedVelocityCandidate.load_json(candidate_path)
    correction = KokunoCompleteCurlCorrection()
    points = _held_out_points(correction, seed=seed, count=point_count)
    contract = PhaseMeanDefectContract(phase_count=8)

    rows = []
    for time in (0.375, 0.5, 0.625):
        sample = contract.evaluate(candidate.at_points, correction, points, time)
        rows.append({"time": time, **sample.metrics()})

    sample8 = contract.evaluate(candidate.at_points, correction, points, 0.5)
    sample16 = replace(contract, phase_count=16).evaluate(candidate.at_points, correction, points, 0.5)
    projector_difference = sample8.mean_defect_increment - sample16.mean_defect_increment
    projector_reference = _vector_rms(sample16.mean_defect_increment)

    half_correction = replace(correction, amplitude=0.5 * correction.amplitude)
    sample_half = contract.evaluate(candidate.at_points, half_correction, points, 0.5)
    full_rms = _vector_rms(sample8.mean_defect_increment)
    half_rms = _vector_rms(sample_half.mean_defect_increment)

    report = {
        "task": "KOKUNO-A3-MEAN-DEFECT-CONTRACT-001",
        "source": {
            "reader": "KokunoYumeto corrected 208-page reconstruction",
            "edition": "2026.09.09-consolidated",
            "doi": "10.5281/zenodo.22678406",
            "source_structure": "MC11-MC12 retain W^{ab}=<w_a w_b> in the mean momentum residual",
            "adapter": "uniform phase-shift mean for the autonomous Agent-2 Cartesian phase; not paper-exact angular/auxiliary averaging",
        },
        "candidate_path": str(candidate_path),
        "candidate_sha256": candidate.sha256,
        "correction": correction.metadata(),
        "sampling": {
            "seed": seed,
            "point_count": point_count,
            "times": [0.375, 0.5, 0.625],
            "phase_count": contract.phase_count,
            "nu": contract.nu,
            "derivative_step": contract.step,
            "time_bounds": list(contract.time_bounds),
            "points_are_optimization_samples": False,
        },
        "rows": rows,
        "projector_refinement": {
            "phase_count_coarse": 8,
            "phase_count_fine": 16,
            "mean_increment_difference_rms": _vector_rms(projector_difference),
            "relative_to_16_phase_mean_increment": _vector_rms(projector_difference) / max(projector_reference, np.finfo(float).tiny),
        },
        "quadratic_scaling_check": {
            "full_amplitude": correction.amplitude,
            "half_amplitude": half_correction.amplitude,
            "half_over_full_mean_increment_rms": half_rms / max(full_rms, np.finfo(float).tiny),
            "quadratic_reference_ratio": 0.25,
        },
        "truth_boundary": {
            "consumes_real_candidate_artifact": True,
            "uses_independent_validation_operator": True,
            "surrogate_defect_used": False,
            "mean_correction_applied": False,
            "radial_stress_inverse_applied": False,
            "finite_correction_cycle_run": False,
            "formal_pde_gate_assessed": False,
            "pde_validated": False,
            "paper_exact": False,
            "openai_field_identified": False,
        },
    }
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2) + "\n")
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract the real phase-mean NS defect increment of the Agent-2 curl correction")
    parser.add_argument("--candidate", default="artifacts/bipolar_joint_capped/candidate.json")
    parser.add_argument("--output", default="artifacts/kokuno_agent3/mean_defect_report.json")
    parser.add_argument("--seed", type=int, default=9172703)
    parser.add_argument("--points", type=int, default=128)
    args = parser.parse_args()
    report = generate_current_candidate_report(candidate_path=args.candidate, output=args.output, seed=args.seed, point_count=args.points)
    summary = {
        "candidate_sha256": report["candidate_sha256"],
        "rows": report["rows"],
        "projector_refinement": report["projector_refinement"],
        "quadratic_scaling_check": report["quadratic_scaling_check"],
    }
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
